/******************************************************************************
 * File Name   : MX_Device.h
 * Date        : 03/03/2022 15:25:19
 * Description : STM32Cube MX parameter definitions
 * Note        : This file is generated by STM32CubeMX (DO NOT EDIT!)
 ******************************************************************************/

#ifndef __MX_DEVICE_H
#define __MX_DEVICE_H

/*---------------------------- Clock Configuration ---------------------------*/

#define MX_LSI_VALUE                            32000
#define MX_LSE_VALUE                            32768
#define MX_HSI_VALUE                            16000000
#define MX_HSE_VALUE                            25000000
#define MX_EXTERNAL_CLOCK_VALUE                 12288000
#define MX_PLLCLKFreq_Value                     150000000
#define MX_SYSCLKFreq_VALUE                     150000000
#define MX_HCLKFreq_Value                       150000000
#define MX_FCLKCortexFreq_Value                 150000000
#define MX_CortexFreq_Value                     150000000
#define MX_AHBFreq_Value                        150000000
#define MX_APB1Freq_Value                       37500000
#define MX_APB2Freq_Value                       75000000
#define MX_APB1TimFreq_Value                    75000000
#define MX_APB2TimFreq_Value                    150000000
#define MX_48MHZClocksFreq_Value                75000000
#define MX_EthernetFreq_Value                   150000000
#define MX_I2SClocksFreq_Value                  96000000
#define MX_RTCFreq_Value                        32000
#define MX_WatchDogFreq_Value                   32000
#define MX_MCO1PinFreq_Value                    50000000
#define MX_MCO2PinFreq_Value                    150000000

/*-------------------------------- CAN1       --------------------------------*/

#define MX_CAN1                                 1

/* GPIO Configuration */

/* Pin PD0 */
#define MX_CAN1_RX_GPIO_Speed                   GPIO_SPEED_FREQ_VERY_HIGH
#define MX_CAN1_RX_Pin                          PD0
#define MX_CAN1_RX_GPIOx                        GPIOD
#define MX_CAN1_RX_GPIO_PuPd                    GPIO_NOPULL
#define MX_CAN1_RX_GPIO_Pin                     GPIO_PIN_0
#define MX_CAN1_RX_GPIO_AF                      GPIO_AF9_CAN1
#define MX_CAN1_RX_GPIO_Mode                    GPIO_MODE_AF_PP

/* Pin PD1 */
#define MX_CAN1_TX_GPIO_Speed                   GPIO_SPEED_FREQ_VERY_HIGH
#define MX_CAN1_TX_Pin                          PD1
#define MX_CAN1_TX_GPIOx                        GPIOD
#define MX_CAN1_TX_GPIO_PuPd                    GPIO_NOPULL
#define MX_CAN1_TX_GPIO_Pin                     GPIO_PIN_1
#define MX_CAN1_TX_GPIO_AF                      GPIO_AF9_CAN1
#define MX_CAN1_TX_GPIO_Mode                    GPIO_MODE_AF_PP

/* NVIC Configuration */

/* NVIC CAN1_RX0_IRQn */
#define MX_CAN1_RX0_IRQn_interruptPremptionPriority 3
#define MX_CAN1_RX0_IRQn_PriorityGroup          NVIC_PRIORITYGROUP_4
#define MX_CAN1_RX0_IRQn_Subriority             0

/* NVIC CAN1_RX1_IRQn */
#define MX_CAN1_RX1_IRQn_interruptPremptionPriority 3
#define MX_CAN1_RX1_IRQn_PriorityGroup          NVIC_PRIORITYGROUP_4
#define MX_CAN1_RX1_IRQn_Subriority             0

/*-------------------------------- CAN2       --------------------------------*/

#define MX_CAN2                                 1

/* GPIO Configuration */

/* Pin PB5 */
#define MX_CAN2_RX_GPIO_Speed                   GPIO_SPEED_FREQ_VERY_HIGH
#define MX_CAN2_RX_Pin                          PB5
#define MX_CAN2_RX_GPIOx                        GPIOB
#define MX_CAN2_RX_GPIO_PuPd                    GPIO_NOPULL
#define MX_CAN2_RX_GPIO_Pin                     GPIO_PIN_5
#define MX_CAN2_RX_GPIO_AF                      GPIO_AF9_CAN2
#define MX_CAN2_RX_GPIO_Mode                    GPIO_MODE_AF_PP

/* Pin PB6 */
#define MX_CAN2_TX_GPIO_Speed                   GPIO_SPEED_FREQ_VERY_HIGH
#define MX_CAN2_TX_Pin                          PB6
#define MX_CAN2_TX_GPIOx                        GPIOB
#define MX_CAN2_TX_GPIO_PuPd                    GPIO_NOPULL
#define MX_CAN2_TX_GPIO_Pin                     GPIO_PIN_6
#define MX_CAN2_TX_GPIO_AF                      GPIO_AF9_CAN2
#define MX_CAN2_TX_GPIO_Mode                    GPIO_MODE_AF_PP

/* NVIC Configuration */

/* NVIC CAN2_RX0_IRQn */
#define MX_CAN2_RX0_IRQn_interruptPremptionPriority 3
#define MX_CAN2_RX0_IRQn_PriorityGroup          NVIC_PRIORITYGROUP_4
#define MX_CAN2_RX0_IRQn_Subriority             0

/* NVIC CAN2_RX1_IRQn */
#define MX_CAN2_RX1_IRQn_interruptPremptionPriority 3
#define MX_CAN2_RX1_IRQn_PriorityGroup          NVIC_PRIORITYGROUP_4
#define MX_CAN2_RX1_IRQn_Subriority             0

/*-------------------------------- CRC        --------------------------------*/

#define MX_CRC                                  1

/* GPIO Configuration */

/*-------------------------------- ETH        --------------------------------*/

#define MX_ETH                                  1

/* GPIO Configuration */

/* Pin PA1 */
#define MX_ETH_REF_CLK_GPIO_Speed               GPIO_SPEED_FREQ_VERY_HIGH
#define MX_ETH_REF_CLK_Pin                      PA1
#define MX_ETH_REF_CLK_GPIOx                    GPIOA
#define MX_ETH_REF_CLK_GPIO_PuPd                GPIO_NOPULL
#define MX_ETH_REF_CLK_GPIO_Pin                 GPIO_PIN_1
#define MX_ETH_REF_CLK_GPIO_AF                  GPIO_AF11_ETH
#define MX_ETH_REF_CLK_GPIO_Mode                GPIO_MODE_AF_PP

/* Pin PA7 */
#define MX_ETH_CRS_DV_GPIO_Speed                GPIO_SPEED_FREQ_VERY_HIGH
#define MX_ETH_CRS_DV_Pin                       PA7
#define MX_ETH_CRS_DV_GPIOx                     GPIOA
#define MX_ETH_CRS_DV_GPIO_PuPd                 GPIO_NOPULL
#define MX_ETH_CRS_DV_GPIO_Pin                  GPIO_PIN_7
#define MX_ETH_CRS_DV_GPIO_AF                   GPIO_AF11_ETH
#define MX_ETH_CRS_DV_GPIO_Mode                 GPIO_MODE_AF_PP

/* Pin PC4 */
#define MX_ETH_RXD0_GPIO_Speed                  GPIO_SPEED_FREQ_VERY_HIGH
#define MX_ETH_RXD0_Pin                         PC4
#define MX_ETH_RXD0_GPIOx                       GPIOC
#define MX_ETH_RXD0_GPIO_PuPd                   GPIO_NOPULL
#define MX_ETH_RXD0_GPIO_Pin                    GPIO_PIN_4
#define MX_ETH_RXD0_GPIO_AF                     GPIO_AF11_ETH
#define MX_ETH_RXD0_GPIO_Mode                   GPIO_MODE_AF_PP

/* Pin PC5 */
#define MX_ETH_RXD1_GPIO_Speed                  GPIO_SPEED_FREQ_VERY_HIGH
#define MX_ETH_RXD1_Pin                         PC5
#define MX_ETH_RXD1_GPIOx                       GPIOC
#define MX_ETH_RXD1_GPIO_PuPd                   GPIO_NOPULL
#define MX_ETH_RXD1_GPIO_Pin                    GPIO_PIN_5
#define MX_ETH_RXD1_GPIO_AF                     GPIO_AF11_ETH
#define MX_ETH_RXD1_GPIO_Mode                   GPIO_MODE_AF_PP

/* Pin PB11 */
#define MX_ETH_TX_EN_GPIO_Speed                 GPIO_SPEED_FREQ_VERY_HIGH
#define MX_ETH_TX_EN_Pin                        PB11
#define MX_ETH_TX_EN_GPIOx                      GPIOB
#define MX_ETH_TX_EN_GPIO_PuPd                  GPIO_NOPULL
#define MX_ETH_TX_EN_GPIO_Pin                   GPIO_PIN_11
#define MX_ETH_TX_EN_GPIO_AF                    GPIO_AF11_ETH
#define MX_ETH_TX_EN_GPIO_Mode                  GPIO_MODE_AF_PP

/* Pin PA2 */
#define MX_ETH_MDIO_GPIO_Speed                  GPIO_SPEED_FREQ_VERY_HIGH
#define MX_ETH_MDIO_Pin                         PA2
#define MX_ETH_MDIO_GPIOx                       GPIOA
#define MX_ETH_MDIO_GPIO_PuPd                   GPIO_NOPULL
#define MX_ETH_MDIO_GPIO_Pin                    GPIO_PIN_2
#define MX_ETH_MDIO_GPIO_AF                     GPIO_AF11_ETH
#define MX_ETH_MDIO_GPIO_Mode                   GPIO_MODE_AF_PP

/* Pin PB13 */
#define MX_ETH_TXD1_GPIO_Speed                  GPIO_SPEED_FREQ_VERY_HIGH
#define MX_ETH_TXD1_Pin                         PB13
#define MX_ETH_TXD1_GPIOx                       GPIOB
#define MX_ETH_TXD1_GPIO_PuPd                   GPIO_NOPULL
#define MX_ETH_TXD1_GPIO_Pin                    GPIO_PIN_13
#define MX_ETH_TXD1_GPIO_AF                     GPIO_AF11_ETH
#define MX_ETH_TXD1_GPIO_Mode                   GPIO_MODE_AF_PP

/* Pin PB12 */
#define MX_ETH_TXD0_GPIO_Speed                  GPIO_SPEED_FREQ_VERY_HIGH
#define MX_ETH_TXD0_Pin                         PB12
#define MX_ETH_TXD0_GPIOx                       GPIOB
#define MX_ETH_TXD0_GPIO_PuPd                   GPIO_NOPULL
#define MX_ETH_TXD0_GPIO_Pin                    GPIO_PIN_12
#define MX_ETH_TXD0_GPIO_AF                     GPIO_AF11_ETH
#define MX_ETH_TXD0_GPIO_Mode                   GPIO_MODE_AF_PP

/* Pin PC1 */
#define MX_ETH_MDC_GPIO_Speed                   GPIO_SPEED_FREQ_VERY_HIGH
#define MX_ETH_MDC_Pin                          PC1
#define MX_ETH_MDC_GPIOx                        GPIOC
#define MX_ETH_MDC_GPIO_PuPd                    GPIO_NOPULL
#define MX_ETH_MDC_GPIO_Pin                     GPIO_PIN_1
#define MX_ETH_MDC_GPIO_AF                      GPIO_AF11_ETH
#define MX_ETH_MDC_GPIO_Mode                    GPIO_MODE_AF_PP

/* NVIC Configuration */

/* NVIC ETH_IRQn */
#define MX_ETH_IRQn_interruptPremptionPriority  4
#define MX_ETH_IRQn_PriorityGroup               NVIC_PRIORITYGROUP_4
#define MX_ETH_IRQn_Subriority                  0

/*-------------------------------- IWDG       --------------------------------*/

#define MX_IWDG                                 1

/* GPIO Configuration */

/*-------------------------------- SPI2       --------------------------------*/

#define MX_SPI2                                 1

/* GPIO Configuration */

/* Pin PB10 */
#define MX_SPI2_SCK_GPIO_Speed                  GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SPI2_SCK_Pin                         PB10
#define MX_SPI2_SCK_GPIOx                       GPIOB
#define MX_SPI2_SCK_GPIO_PuPd                   GPIO_NOPULL
#define MX_SPI2_SCK_GPIO_Pin                    GPIO_PIN_10
#define MX_SPI2_SCK_GPIO_AF                     GPIO_AF5_SPI2
#define MX_SPI2_SCK_GPIO_Mode                   GPIO_MODE_AF_PP

/* Pin PC2 */
#define MX_SPI2_MISO_GPIO_Speed                 GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SPI2_MISO_Pin                        PC2
#define MX_SPI2_MISO_GPIOx                      GPIOC
#define MX_SPI2_MISO_GPIO_PuPd                  GPIO_NOPULL
#define MX_SPI2_MISO_GPIO_Pin                   GPIO_PIN_2
#define MX_SPI2_MISO_GPIO_AF                    GPIO_AF5_SPI2
#define MX_SPI2_MISO_GPIO_Mode                  GPIO_MODE_AF_PP

/* Pin PC3 */
#define MX_SPI2_MOSI_GPIO_Speed                 GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SPI2_MOSI_Pin                        PC3
#define MX_SPI2_MOSI_GPIOx                      GPIOC
#define MX_SPI2_MOSI_GPIO_PuPd                  GPIO_NOPULL
#define MX_SPI2_MOSI_GPIO_Pin                   GPIO_PIN_3
#define MX_SPI2_MOSI_GPIO_AF                    GPIO_AF5_SPI2
#define MX_SPI2_MOSI_GPIO_Mode                  GPIO_MODE_AF_PP

/*-------------------------------- SYS        --------------------------------*/

#define MX_SYS                                  1

/* GPIO Configuration */

/* Pin PA13 */
#define MX_SYS_JTMS_SWDIO_Pin                   PA13

/* Pin PA14 */
#define MX_SYS_JTCK_SWCLK_Pin                   PA14

/*-------------------------------- NVIC       --------------------------------*/

#define MX_NVIC                                 1

/*-------------------------------- GPIO       --------------------------------*/

#define MX_GPIO                                 1

/* GPIO Configuration */

/* Pin PD7 */
#define MX_PD7_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PD7_Pin                              PD7
#define MX_PD7_GPIOx                            GPIOD
#define MX_PD7_PinState                         GPIO_PIN_RESET
#define MX_PD7_GPIO_PuPd                        GPIO_NOPULL
#define MX_RS485DE                              PD7
#define MX_PD7_GPIO_Pin                         GPIO_PIN_7
#define MX_PD7_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PA6 */
#define MX_PA6_Pin                              PA6
#define MX_PA6_GPIOx                            GPIOA
#define MX_PA6_GPIO_PuPd                        GPIO_PULLUP
#define MX_EMERG_R                              PA6
#define MX_PA6_GPIO_Pin                         GPIO_PIN_6
#define MX_PA6_GPIO_Mode                        GPIO_MODE_INPUT

/* Pin PA5 */
#define MX_PA5_Pin                              PA5
#define MX_PA5_GPIOx                            GPIOA
#define MX_PA5_GPIO_PuPd                        GPIO_PULLUP
#define MX_EMERG_F                              PA5
#define MX_PA5_GPIO_Pin                         GPIO_PIN_5
#define MX_PA5_GPIO_Mode                        GPIO_MODE_INPUT

/* Pin PB1 */
#define MX_PB1_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PB1_Pin                              PB1
#define MX_PB1_GPIOx                            GPIOB
#define MX_PB1_PinState                         GPIO_PIN_SET
#define MX_PB1_GPIO_PuPd                        GPIO_NOPULL
#define MX_BRAKE_B                              PB1
#define MX_PB1_GPIO_Pin                         GPIO_PIN_1
#define MX_PB1_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PE3 */
#define MX_PE3_GPIO_Speed                       GPIO_SPEED_FREQ_VERY_HIGH
#define MX_PE3_Pin                              PE3
#define MX_PE3_GPIOx                            GPIOE
#define MX_PE3_PinState                         GPIO_PIN_SET
#define MX_PE3_GPIO_PuPd                        GPIO_NOPULL
#define MX_FLASH_CS                             PE3
#define MX_PE3_GPIO_Pin                         GPIO_PIN_3
#define MX_PE3_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PB0 */
#define MX_PB0_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PB0_Pin                              PB0
#define MX_PB0_GPIOx                            GPIOB
#define MX_PB0_PinState                         GPIO_PIN_SET
#define MX_PB0_GPIO_PuPd                        GPIO_NOPULL
#define MX_BRAKE_A                              PB0
#define MX_PB0_GPIO_Pin                         GPIO_PIN_0
#define MX_PB0_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

#endif  /* __MX_DEVICE_H */

